name:                hs-server
version:             0.1.0.0
github:              "githubuser/hs-server"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Alexis Crespo"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hs-server#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- postgresql-simple
- servant-server
- servant-websockets
- text
- time
- wai
- wai-cors
- warp
- websockets

library:
  source-dirs: src

executables:
  hs-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hs-server

tests:
  hs-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hs-server
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
